In [2]:
import numpy as np


It is the basic Neural Network with forward propagation only, not Backpropagation

In [14]:
X=[[3,2,1,4],
   [9,8,7,6],
   [7,6,4,3],
   [6,7,4,3]];

In [18]:
class Dense():
  def __init__(self,inputs,neurons):
    self.weights=0.10*np.random.randn(inputs,neurons)
    self.biases=np.zeros((1,neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights) +self.biases

In [19]:
layer1= Dense(4,5)

In [20]:
layer1

In [22]:
layer1.forward(X)

In [23]:
print(layer1.output)

[[-0.35387222 -0.55294679 -0.02382586  0.11173988  0.47323901]
 [-1.51710277 -1.52352611  0.22220704 -0.03595499 -0.05301024]
 [-1.25907039 -1.22267235  0.07225518 -0.11200345  0.07073597]
 [-1.22855845 -1.03179902 -0.05206213 -0.24678803 -0.05958609]]


Applied Relu activation function to reduce value to zero,if they are less than zero.

In [25]:
class Relu():
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)
  

In [27]:
activation=Relu()

In [28]:
activation.forward(layer1.output)

In [29]:
print(activation.output)

[[0.         0.         0.         0.11173988 0.47323901]
 [0.         0.         0.22220704 0.         0.        ]
 [0.         0.         0.07225518 0.         0.07073597]
 [0.         0.         0.         0.         0.        ]]
